import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ThemeProvider from "./theme";
import localFont from "vinext/shims/font-local";

const futura = localFont({
  src: [
    // Light (300)
    { path: "./FuturaLT-CondensedLight.woff2", weight: "300", style: "normal" },
    { path: "./FuturaLT-CondensedLightObl.woff2", weight: "300", style: "italic" },

    // Medium (500)
    { path: "./FuturaLT-Condensed.woff2", weight: "500", style: "normal" },
    { path: "./FuturaLT-CondensedOblique.woff2", weight: "500", style: "italic" },

    // Bold (700)
    { path: "./FuturaLT-CondensedBold.woff2", weight: "700", style: "normal" },
    { path: "./FuturaLT-CondensedBoldOblique.woff2", weight: "700", style: "italic" },

    // Extra Bold (800)
    { path: "./FuturaLT-CondensedExtraBold.woff2", weight: "800", style: "normal" },
    { path: "./FuturaLT-CondExtraBoldObl.woff2", weight: "800", style: "italic" },
  ],
  variable: "--font-futura",
});

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(futura.variable)} suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}