import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ThemeProvider from "./theme";
import localFont from "vinext/shims/font-local";

const futura = localFont({
  src: [
    { path: "./FuturaLT-CondensedMedium.ttf", weight: "500", style: "normal" },
    { path: "./FuturaLT-CondensedExtraBold.ttf", weight: "800", style: "bold" },
  ],
  variable: "--font-futura",
});

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(futura.variable)} suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}